[project]
name = 'startex-contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.competition]
path = 'contracts/competition.clar'
clarity_version = 3
epoch = 'latest'

[contracts.scoring-system]
path = 'contracts/scoring-system.clar'
clarity_version = 3
epoch = 'latest'

[contracts.startup-registry]
path = 'contracts/startup-registry.clar'
clarity_version = 3
epoch = 'latest'

[contracts.token-factory]
path = 'contracts/token-factory.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
