[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10
co
[accounts.deployer]
mnemonic = "immune click monster example quiz accuse bulk credit teach marriage demise bread behave slow wasp border immense hotel update fee coach core shoot intact"
