[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "trust wood assault goose rifle foil vehicle bomb color cinnamon shed outdoor recall price slot sketch dust reject announce vicious robust forum flee item"
